server {
    # Écouter sur le port 443 pour les connexions sécurisées SSL (IPv4 et IPv6)
    listen 443 ssl;
    listen [::]:443 ssl;

    # Le nom de domaine requis par le sujet
    server_name masenche.42.fr;

    # Emplacement des certificats SSL générés par le script
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # Protocoles TLS imposés par le sujet (v1.2 et v1.3 uniquement)
    ssl_protocols TLSv1.2 TLSv1.3;

    # Racine du site et fichiers par défaut (partagés avec le volume WordPress)
    root /var/www/wordpress;
    index index.php index.html index.htm;

    # Gestion des requêtes principales
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    # Redirection des fichiers PHP vers le conteneur WordPress via le port 9000
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
